### ISSUE TITLE
Error message when trying to show all answers

### ISSUE THREAD

**Issue by danmlevy** [ggjara/teachvatory#61]
Error message when trying to show all answers

<img width="1433" alt="image" src="https://github.com/user-attachments/assets/521a6f52-34df-44b6-a719-4f44a27acfd6">

**Comment by RRMaximiliano** [comment]
I am unable to reproduce this error. Let's discuss during our meeting what's going on here.

**Comment by RRMaximiliano** [comment]
Closing this issue until we reproduce it again.
